Completed css-grid-classes | Mohamed Elmessiry
Mohamed-Elmessiry/c0121-code-solutions pull request #17
Opened 2021-01-22 02:47 UTC by Mohamed-Elmessiry

![Screen Shot 2021-01-21 at 9 46 52 PM](https://user-images.githubusercontent.com/69738204/105439151-4d4dda00-5c32-11eb-9d42-54dcbab73707.png)

2021-01-22 19:10 UTC, codingcodymiller requested changes
You only have one grid class right now, supposedly for a column that is one third of the size available. This is only working right now because flex containers do not allow more than one row, so it is adjusting their size for you. You will need to add a column class for each size of column needed, do not let flexbox clean up your mess for you 😁

2021-01-22 19:10 UTC, codingcodymiller commented on css-grid-classes/index.html
> +      <div class="column-thrid">
typo

2021-01-22 19:10 UTC, codingcodymiller commented on css-grid-classes/index.html
> +      <div class="column-thrid">
typo

2021-01-22 19:10 UTC, codingcodymiller commented on css-grid-classes/index.html
> +      <div class="column-thrid">
typo

2021-01-22 19:10 UTC, codingcodymiller commented on css-grid-classes/style.css
> +.column-thrid{
typo

2021-01-23 21:14 UTC, Mohamed-Elmessiry commented
> You only have one grid class right now, supposedly for a column that is one third of the size available. This is only working right now because flex containers do not allow more than one row, so it is adjusting their size for you. You will need to add a column class for each size of column needed, do not let flexbox clean up your mess for you 😁

Hi Cody, just to make sure I am getting this correctly. Do you need me to add a  a div, which would be a parent of <div class:column-third>, and a child to the <div class:row> ?

2021-01-26 21:09 UTC, codingcodymiller requested changes

2021-01-26 21:09 UTC, codingcodymiller commented on css-grid-classes/style.css
> +}
You're also going to need a `.column-fourth` and a `.column-two-thirds` classes. These will be used for the other sections with different widths.

2021-02-25 23:49 UTC, closed without merging