Still work in progress String Manipulation 1 |Mohamed Elmessiry
Mohamed-Elmessiry/c0121-code-solutions pull request #36
Opened 2021-01-30 19:35 UTC by Mohamed-Elmessiry

2021-01-30 19:36 UTC, thebearingedge requested changes
Hi Mohamed, please wait until your solution is complete before opening a Pull Request.

2021-02-01 00:01 UTC, Mohamed-Elmessiry commented
Hi Tim ,

I am sorry, was just scared from making mistakes on the terminal over the weekend :)
![Screen Shot 2021-01-31 at 6 42 14 PM](https://user-images.githubusercontent.com/69738204/106402264-b08bf900-63f6-11eb-94fa-7df16a49f60e.png)
![Screen Shot 2021-01-31 at 6 42 30 PM](https://user-images.githubusercontent.com/69738204/106402266-b386e980-63f6-11eb-855c-a792af03ead4.png)

2021-02-01 01:04 UTC, thebearingedge requested changes

2021-02-01 01:04 UTC, thebearingedge commented on string-manipulation-1/src/capitalize.js
> +// }
Please remove all commented code before turning in. You have some in some other files too.

2021-02-01 17:06 UTC, thebearingedge approved these changes

2021-02-25 23:47 UTC, closed without merging